# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44a3ad5f2fe5603843f5067e8afeb97b646dbd4533ff53a3f90f5b8ac4accc05b3ff4431a21976141d9a06a91b6dda9e20c0cdc895ce2fd4cd55bcd88d7ee698

test:
  secret_key_base: 45d03d2a6d90c2b87c913464c53d4de7280e2cb50013686841f7a749df1b3471876799fcf4357b71e8b637c4aa5aeac37382f957b612e1213613f95cebffb3e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
